const jobData = [
  {
    _id: "1",
    title: "Quality Assurance",
    job_description: "Handling backend stuff and cloud is a plust point (AWS)",
    job_qualification: "Java, Springboot, React, Next",
    job_type: "Full Time",
    job_tenure: "Contract",
    job_status: 1,
    company_name: "Netflix",
    company_image_url:
      "https://upload.wikimedia.org/wikipedia/commons/7/75/Netflix_icon.svg",
    company_city: "Seattle",
    salary_min: 4000000,
    salary_max: 10000000,
    createdAt: "2024-09-17T13:40:26.026Z",
    __v: 0,
  },
  {
    _id: "2",
    title: "Frontend Developer",
    job_description: "Develop responsive user interfaces for web applications.",
    job_qualification: "HTML, CSS, JavaScript, React, Vue.js",
    job_type: "Remote",
    job_tenure: "Full-time",
    job_status: 1,
    company_name: "GoTo Group",
    company_image_url:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/GoTo_logo.svg/1200px-GoTo_logo.svg.png",
    company_city: "Jakarta",
    salary_min: 8000000,
    salary_max: 15000000,
    createdAt: "2024-10-16T04:30:28.597Z",
    __v: 0,
  },
  {
    _id: "3",
    title: "Data Scientist",
    job_description: "Analyze data to help drive business decisions.",
    job_qualification: "Python, SQL, Machine Learning, Data Visualization",
    job_type: "Hybrid",
    job_tenure: "Full-time",
    job_status: 1,
    company_name: "Traveloka",
    company_image_url:
      "https://avatars.githubusercontent.com/u/1683964?s=280&v=4",
    company_city: "Jakarta",
    salary_min: 12000000,
    salary_max: 20000000,
    createdAt: "2024-10-16T04:32:05.844Z",
    __v: 0,
  },
  {
    _id: "4",
    title: "Product Manager",
    job_description: "Oversee product development from ideation to launch.",
    job_qualification: "Project Management, UX/UI, Agile, SCRUM",
    job_type: "Remote",
    job_tenure: "Full-time",
    job_status: 1,
    company_name: "OVO",
    company_image_url: "https://pbs.twimg.com/media/EUbePLEU0AIpder.jpg",
    company_city: "Jakarta",
    salary_min: 15000000,
    salary_max: 25000000,
    createdAt: "2024-10-16T04:35:24.036Z",
    __v: 0,
  },
];

export { jobData };
