const jobData = [
  {
    _id: 1,
    title: "Quality Assurance",
    job_description: "Handling backend stuff and cloud is a plust point (AWS)",
    job_qualification: "Java, Springboot, React, Next",
    job_type: "Full Time",
    job_tenure: "Contract",
    job_status: 1,
    company_name: "Netflix",
    company_image_url:
      "https://upload.wikimedia.org/wikipedia/commons/7/75/Netflix_icon.svg",
    company_city: "Seattle",
    salary_min: 4000000,
    salary_max: 10000000,
    createdAt: "2024-09-17T13:40:26.026Z",
  },
  {
    _id: 2,
    title: "Frontend Developer",
    job_description: "Develop responsive user interfaces for web applications.",
    job_qualification: "HTML, CSS, JavaScript, React, Vue.js",
    job_type: "Remote",
    job_tenure: "Full-time",
    job_status: 1,
    company_name: "GoTo Group",
    company_image_url:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/GoTo_logo.svg/1200px-GoTo_logo.svg.png",
    company_city: "Jakarta",
    salary_min: 8000000,
    salary_max: 15000000,
    createdAt: "2024-10-16T04:30:28.597Z",
  },
  {
    _id: 3,
    title: "Data Scientist",
    job_description: "Analyze data to help drive business decisions.",
    job_qualification: "Python, SQL, Machine Learning, Data Visualization",
    job_type: "Hybrid",
    job_tenure: "Full-time",
    job_status: 1,
    company_name: "Traveloka",
    company_image_url:
      "https://avatars.githubusercontent.com/u/1683964?s=280&v=4",
    company_city: "Jakarta",
    salary_min: 12000000,
    salary_max: 20000000,
    createdAt: "2024-10-16T04:32:05.844Z",
  },
  {
    _id: 4,
    title: "Product Manager",
    job_description: "Oversee product development from ideation to launch.",
    job_qualification: "Project Management, UX/UI, Agile, SCRUM",
    job_type: "Remote",
    job_tenure: "Full-time",
    job_status: 1,
    company_name: "OVO",
    company_image_url: "https://pbs.twimg.com/media/EUbePLEU0AIpder.jpg",
    company_city: "Jakarta",
    salary_min: 15000000,
    salary_max: 25000000,
    createdAt: "2024-10-16T04:35:24.036Z",
  },
  {
    _id: 5,
    title: "Frontend Developer",
    job_description: "Make a website",
    job_qualification: "Node.js, Express, MongoDB, RESTful APIs",
    job_type: "On-site",
    job_tenure: "Contract",
    job_status: 1,
    company_name: "PERTAMINA",
    company_image_url:
      "https://storage.googleapis.com/ind-mengajar/images/mitra/pertamina.png?ver=20240818",
    company_city: "Jakarta",
    salary_min: 20000000,
    salary_max: 21000000,
    createdAt: "2024-10-16T12:58:59.042Z",
  },
  {
    _id: 6,
    title: "Supir Bus",
    job_description: "Menyupir bus",
    job_qualification: "SIM B",
    job_type: "Remote",
    job_tenure: "Full-time",
    job_status: 1,
    company_name: "Transjakarta",
    company_image_url:
      "https://storage.googleapis.com/ind-mengajar/images/mitra/TJ.jpg?ver=20240818",
    company_city: "Bandung",
    salary_min: 8000000,
    salary_max: 10000000,
    createdAt: "2024-10-16T13:01:05.127Z",
  },
  {
    _id: 7,
    title: "UI/UX Designer",
    job_description: "mendesain tampilan web yg menarik dan responsif",
    job_qualification: "Figma, Adobe Illustrator, HTML, CSS",
    job_type: "Onsite",
    job_tenure: "Full Time",
    job_status: 1,
    company_name: "MU Tech",
    company_image_url:
      "https://himatif.ilkom.unej.ac.id/storage/photo/post/E8lmhI9FEzl479ZwUrNPxLd7hopF6nxNhMesQtWq.png",
    company_city: "Denpasar",
    salary_min: 2000000,
    salary_max: 5000000,
    createdAt: "2024-10-20T08:26:07.036Z",
  },
  {
    _id: 8,
    title: "WISATA",
    job_description: "WISATA",
    job_qualification: "DESSA",
    job_type: "SEDA",
    job_tenure: "10",
    job_status: 1,
    company_name: "PT. WISTA BALI",
    company_image_url:
      "https://png.pngtree.com/png-vector/20230304/ourmid/pngtree-pura-bali-realistic-high-details-vector-png-image_6630005.png",
    company_city: "bali",
    salary_min: 100000,
    salary_max: 100000,
    createdAt: "2024-11-11T04:27:19.600Z",
  },
  {
    _id: 9,
    title: "Full Stack Developer",
    job_description: "make a web app",
    job_qualification: "Java, Springboot, React, Next, golang, ",
    job_type: "Full time",
    job_tenure: "Contract",
    job_status: 0,
    company_name: "PT. Hyundai motor Manufacturing Indonesia",
    company_image_url:
      "https://hyundaibsd.co.id/wp-content/uploads/2022/08/hyundai-logo.png",
    company_city: "Bekasi",
    salary_min: 5000000,
    salary_max: 10000000,
    createdAt: "2024-11-22T18:01:50.810Z",
  },
  {
    _id: 10,
    title: "Full Stack Engineer",
    job_description:
      "Working with engineering and product owners to refine and develop the product, from concept to implementation.",
    job_qualification:
      "Bachelor’s degree in Computer Science, Software Engineering, or a related field (or equivalent experience).",
    job_type: "Remote",
    job_tenure: "Contract",
    job_status: 1,
    company_name: "PT DIGITAL XCELERATION NUSANTARA",
    company_image_url:
      "https://image-service-cdn.seek.com.au/e5943afe05edb7253d37edf5bf03183ad73d93c7/f3c5292cec0e05e4272d9bf9146f390d366481d0",
    company_city: "Jakarta",
    salary_min: 7000000,
    salary_max: 10000000,
    createdAt: "2024-11-24T08:41:01.685Z",
  },
  {
    _id: 11,
    title: "Risk Management Staff",
    job_description: "Membuat analisa terkait pemenuhan regulasi",
    job_qualification:
      "Memiliki pengetahuan dalam bidang keuangan, perbankan, audit serta memiliki kemampuan analisa yang baik",
    job_type: "Onsite",
    job_tenure: "Contract",
    job_status: 1,
    company_name: "PT Asuransi Jiwa Central Asia Raya (CAR)",
    company_image_url:
      "https://image-service-cdn.seek.com.au/881097bd6844c586bbad032ecfe4fe7d6b8c5710/ee4dce1061f3f616224767ad58cb2fc751b8d2dc",
    company_city: "Jakarta",
    salary_min: 3000000,
    salary_max: 5000000,
    createdAt: "2024-11-24T13:12:01.922Z",
  },
  {
    _id: 12,
    title: "Creative Designer",
    job_description:
      "Create UI mockups and prototypes that effectively demonstrate site functionality and appearance.",
    job_qualification:
      "2+ years of experience as a Graphic Designer or UI Web Designer.",
    job_type: "Remote",
    job_tenure: "Contract",
    job_status: 1,
    company_name: "PT Hashmicro Solusi Indonesia",
    company_image_url:
      "https://image-service-cdn.seek.com.au/6bbe65740ee10c34ccbbdb82397d51e7cd08d84f/f3c5292cec0e05e4272d9bf9146f390d366481d0",
    company_city: "Bandung",
    salary_min: 6000000,
    salary_max: 8000000,
    createdAt: "2024-11-24T13:24:19.751Z",
  },
];

export { jobData };
